{
  "formatVersion": "1.1",
  "component": {
    "group": "de.dseelp.kommon",
    "module": "command",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "f7mwrczhfbhdjdb6yvwsx5s5nu"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "command-0.0.1.jar",
          "url": "command-0.0.1.jar",
          "size": 43586,
          "sha512": "0927aff175a60c25e44dc257e1d56e0d3ad56ada882d840b3194bd41622a178bbfae744eddc9888a1dc8374f4875a5c67911e86a6eb73cdb5f4b8cbb8e97bcfe",
          "sha256": "f409b958156e23edfbe2bcde04daf2ecf8af314d1092376af91528d115d8f0b2",
          "sha1": "c3c9757383426b9a1d80368a2465338eaa303019",
          "md5": "6f22e6936b3b08460426cd4bb9774bbb"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "command-0.0.1.jar",
          "url": "command-0.0.1.jar",
          "size": 43586,
          "sha512": "0927aff175a60c25e44dc257e1d56e0d3ad56ada882d840b3194bd41622a178bbfae744eddc9888a1dc8374f4875a5c67911e86a6eb73cdb5f4b8cbb8e97bcfe",
          "sha256": "f409b958156e23edfbe2bcde04daf2ecf8af314d1092376af91528d115d8f0b2",
          "sha1": "c3c9757383426b9a1d80368a2465338eaa303019",
          "md5": "6f22e6936b3b08460426cd4bb9774bbb"
        }
      ]
    }
  ]
}
